stages:
  - build
  - images
  - deploy
    
build-app:
  tags:
    - docker
  stage: build
  image: maven:3-openjdk-11
  script:
    - mkdir -p /root/.m2/repository/org/springframework/
    - mkdir -p /root/.m2/repository/io/
    - unzip static-deps/data.zip -d /root/.m2/repository/org/springframework
    - unzip static-deps/swagger.zip -d /root/.m2/repository/io
    - mvn install -DskipTests
  artifacts:
    paths:
      - target/arcx-0.0.1-SNAPSHOT.jar

admin-api-app:image:build:
  tags:
    - docker
  stage: images
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/admin-api-app/Dockerfile --destination $CI_REGISTRY_IMAGE/admin-api-app:$CI_COMMIT_REF_SLUG

admin-api-web:image:build:
  tags:
    - docker
  stage: images
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/admin-api-web/Dockerfile --destination $CI_REGISTRY_IMAGE/admin-api-web:$CI_COMMIT_REF_SLUG

deploy to dev:
  when: manual
  stage: deploy
  tags:
    - docker
  image: dtzar/helm-kubectl
  script:
    - apk add gettext
    - kubectl config set-cluster dev-cluster --server="$KUBE_URL"
    - kubectl config set-cluster dev-cluster --certificate-authority=$KUBE_CA_PEM_FILE --embed-certs=true
    - kubectl config set-credentials gitlab --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=dev-cluster --user=gitlab --namespace="$KUBE_NAMESPACE"
    - kubectl config use-context default
    - envsubst < k8s/arcx-admin-api-configmap.yml | kubectl apply -f -
    - envsubst < k8s/arcx-admin-api-app.yml | kubectl apply -f -
    - envsubst < k8s/arcx-admin-api-web.yml | kubectl apply -f -
  environment:
    name: development
    url: https://arcx-development-admin-api.devsecops-eval.epa.gov
  only:
    - branches
  except:
    - master
